# name: GitHub Actions Demo
# on: 
#   push:
#     branches:
#       - deploy
# jobs:
#   build-react:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Build and push Docker image
#       uses: docker/build-push-action@v1
#       with:
#         repository: dockertims/sde-job
#         dockerfile: Dockerfile
#         tags: latest

stages:
  - deploy
docker-deploy:
  stage: deploy
  # 执行Job内容
  script:
    - docker build -t sde-job .
    - if [ $(docker ps -aq --filter name = sde-job ) ]; then docker rm -f sde-job;fi

    - docker run -d -p 3000:80 --name sde-job sde-job

    - echo "This job deploys something. It will only run when all jobs in the"
    - echo "test stage complete."
  tags:
    # 执行Job的服务器
    - latest
  only:
    # 只有在master分支才会执行
    - deploy