# name: GitHub Actions Demo
# on: 
#   push:
#     branches:
#       - deploy
# jobs:
#   build-react:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v1
#       with:
#         # username: ${{ secrets.DOCKER_USERNAME }}
#         # password: ${{ secrets.DOCKER_PASSWORD }}
#         repository: dockertims/sde-job-web
#         dockerfile: Dockerfile
#         tags: latest

stages:
  - deploy
docker-deploy:
  stage: deploy
  # 执行Job内容
  script:
    # 通过Dockerfile生成cicd-demo镜像
    - docker build -t sde-job-web .
    # 删除已经在运行的容器
    - if [ $(docker ps -aq --filter name = sde-job-web ) ]; then docker rm -f sde-job-web;fi
    # 通过镜像启动容器，并把本机8000端口映射到容器8000端口
    - docker run -d -p 3000:3000 --name sde-job-web  sde-job-web
    
    - echo "This job deploys something. It will only run when all jobs in the"
    - echo "test stage complete."
  tags:
    # 执行Job的服务器
    - latest
  only:
    # 只有在master分支才会执行
    - deploy